adminlio/urls.py
from django.conf.urls import url
from django.contrib import admin

from sys import path
from django.conf.urls import url,include
from django.contrib import admin
from login.views import LoginAdmin
from adminlio.views import adminhome,savetroquel,findtroqueles,edittroqueles,deletetroqueles,updatetroquel,addcolor,getcolores,CreateGallery,showpost,showimagenes,Listaproductos,getzonesforproduct,EditarProducto,EliminarProducto,repeattroquel,EditGallery,Listagalerias,EliminarGaleria,validate_troquel
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import javascript_catalog
from django.contrib.auth.views import logout


js_info_dict = {
    #domain is default
    'packages': ('adminlio',),
}
urlpatterns = [
    url(r'^$', adminhome.as_view(), name="homeadmin"),
    url(r'^login$', LoginAdmin.as_view(), name="loginadmin"),
    url(r'^savetroquel$',savetroquel , name="savetroquel"),
    url(r'^repeattroquel$',repeattroquel , name="repeattroquel"),
    url(r'^findtroquel$',findtroqueles , name="findtroquel"),
    url(r'^updatetroquel$',updatetroquel , name="updatetroquel"),
    url(r'^creategallery',CreateGallery.as_view() , name="creategallery"),
    url(r'^editgallery/(?P<pk>\d+)$',EditGallery.as_view() , name="editgallery"),
    url(r'^listgallery',Listagalerias , name="listgallery"),
    url(r'^deletegallery/(?P<pk>\d+)$',EliminarGaleria.as_view() , name="deletegallery"),
    url(r'^getcolores$',getcolores, name="getcolores"),
    url(r'^addcolor$',addcolor , name="addcolor"),
    url(r'^edittroqueles/(?P<pk>\d+)$',edittroqueles , name="edittroqueles"),
    url(r'^deletetroqueles/(?P<pk>\d+)$',deletetroqueles , name="deletetroqueles"),
    url(r'^editarproducto/(?P<pk>\d+)$',EditarProducto.as_view(),name="editarproducto"),
    url(r'^elmininarproducto/(?P<pk>\d+)$',EliminarProducto.as_view(),name="eliminarproducto"),

    url(r'^validatetroquel$', validate_troquel, name="validatetroquel"),

    url(r'^listproductos',Listaproductos,name='listproductos'),
    url(r'^zonas$', getzonesforproduct, name="zonas"),
    #url(r'^registro/', AddAdmin.as_view(), name='registroadmin'),
    url(r'^salir$', logout, name="salir", kwargs={'next_page': 'adminlio:loginadmin'})
]

login/urls.py
from django.conf.urls import url
from django.contrib import admin

from sys import path
from django.conf.urls import url,include
from django.contrib import admin
from login.views import Loginusuario, AddUsuario
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import javascript_catalog
from django.contrib.auth.views import logout

js_info_dict = {
    #domain is default
    'packages': ('login',),
}
urlpatterns = [
    url(r'^$', Loginusuario.as_view(), name="login"),
    url(r'^registro/', AddUsuario.as_view(), name='registro'),
    url(r'^salir$', logout, name="salir", kwargs={'next_page': 'login:login'})
]

madebylio/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from base.views import home,showproducts
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import javascript_catalog
from django.contrib.staticfiles.urls import static
from adminlio.views import showimagenes,showpost
from login.views import loginajax,userregajax
from base.views import send_mail,findprodforcategory,savebuy,retrieve_data,fillmobileshopcar,validate_username,cleancookies,savecanvasimage,chargecolors,showsameproducts,test_query,hometeste
from adminlio.views import validate_troquel
from django.contrib.auth.views import logout
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm,password_reset_complete

js_info_dict = {
    #domain is default
    'packages': ('base',),
}
urlpatterns = [

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
        url(_(r'^admin/'), admin.site.urls),
        url(_(r'^login/'), include('login.urls', namespace='login')),
        url(_(r'^adminlio/'), include('adminlio.urls', namespace='adminlio')),
        url(_(r'^pagos/'), include('pagos.urls', namespace='pagos')),
        url(_(r'^$'), home,name='home'),
        url(_(r'^teste'), hometeste,name='hometeste'),
        #url(_(r'^oauth/'), include('social_django.urls', namespace='social')),  # <-- social auth
        url(_(r'accounts/'),include('allauth.urls')),
        url(_(r'^cleancookies$'), cleancookies,name='cleancookies'),
        url(_(r'^showsameproducts$'), showsameproducts,name='showsameproducts'),
        url(_(r'chargecolors$'), chargecolors,name='chargecolors'),
        url(_(r'^savecanvas$'), savecanvasimage,name='savecanvas'),
        url(_(r'^savebuy$'), savebuy,name='savebuy'),
        url(_(r'^testquery$'), test_query,name='testquery'),
        url(_(r'^fillmobileshopcar$'), fillmobileshopcar,name='fillmobileshopcar'),
        url(_(r'^pagos/retrieve_data$'), savebuy,name='retrieve_data'),
        url(r'^send-mail$',send_mail , name="send-mail"),       
        url(r'^loginuser$', loginajax, name="loginuser"),
        url(r'^reguser$', userregajax, name="reguser"),
        url(_(r'^showproducts$'), showproducts,name='showproducts'),
        url(_(r'^validateusername$'), validate_username,name='validateusername'),
        url(_(r'^showimagenes$'),showimagenes, name="showimages"),
        url(_(r'^showgalleries$'),showpost, name="showgalleries"),
        url(_(r'^showprodforcategories'),findprodforcategory,name='showprodforcategories'),
        url(_(r'^salir$'), logout, name="salirhome", kwargs={'next_page': 'home'}),
        #url para recuperar contraseña
        url(_(r'^reset/password_reset/$'),password_reset,{'template_name':'registration/password_reset_form.html','email_template_name':'registration/password_reset_email.html'},name='password_reset'),
                url(_(r'^reset/password_reset_done/$'),password_reset_done,{'template_name':'registration/password_reset_done.html'},name='password_reset_done'),
                url(_(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$'),password_reset_confirm, {'template_name':'registration/password_reset_confirm.html'},name='password_reset_confirm'),
                url(_(r'^reset/done/$'),password_reset_complete,{'template_name':'registration/password_reset_complete.html'},name="password_reset_complete"),
        url(r'^i18n/',include('django.conf.urls.i18n')),
        url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),
)

login/models.py
from django.db import models

# Create your models here.
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

class Usuario(User):
    #color = models.CharField(max_length=10)
    class Meta:
        verbose_name = _('usuario')
        verbose_name_plural = _('usuarios')

login/forms.py
from django.forms import ModelForm, inlineformset_factory
from django import forms
from django.forms.models import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario

class UsuarioForm(UserCreationForm):
    class Meta:
        model = Usuario # modelo a usar
        #campos a utilizar adicionales los agregamos en fields
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            #'color',
        ]
        labels = {
            'username': 'Nombre de usuario',
            'first_name': 'Nombre',
            'last_name': 'Apellidos',
            'email': 'Correo',
            #'color':'color',
        }

login/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView, CreateView, UpdateView, FormView,DeleteView, ListView
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, JsonResponse
from login.models import Usuario
from adminlio.models import UsuarioAdmin
from login.forms import UsuarioForm
from django.contrib.auth import login,authenticate
from django.contrib import  messages
from django.shortcuts import render, render_to_response
from django.views.decorators.csrf import csrf_protect



# Create your views here.

class LoginAdmin(FormView):
    template_name = 'login/loginadmin.html'
    # Le indicamos que el formulario a utilizar es el formulario de autenticación de Django
    form_class = AuthenticationForm
    # Le decimos que cuando se haya completado exitosamente la operación nos redireccione a la url bienvenida de la aplicación personas
    success_url = reverse_lazy("adminlio:homeadmin")

    def dispatch(self, request, *args, **kwargs):
        # Si el usuario está autenticado entonces nos direcciona a la url establecida en success_url
        if self.request.user.is_authenticated() and self.request.user.is_superuser:
            return HttpResponseRedirect(self.get_success_url())
        # Sino lo está entonces nos muestra la plantilla del login simplemente
        else:
            return super(LoginAdmin, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        if(form.get_user().is_superuser):
            login(self.request, form.get_user())
            return super(LoginAdmin, self).form_valid(form)
        else:
            return render(self.request,'adminlio/noperm.html')

    def get_context_data(self, **kwargs):
        context = super(LoginAdmin, self).get_context_data(**kwargs)
        usuarios = UsuarioAdmin.objects.all()
        context['datos_user'] = usuarios
        return context

class Loginusuario(FormView): #Login convencional donde pueden entrar usuarios normales(usuarios,asesores,publicadores)
    # Establecemos la plantilla a utilizar
    template_name = 'login/login.html'
    # Le indicamos que el formulario a utilizar es el formulario de autenticación de Django
    form_class = AuthenticationForm
    # Le decimos que cuando se haya completado exitosamente la operación nos redireccione a la url bienvenida de la aplicación personas
    success_url = reverse_lazy("home")


    def dispatch(self, request, *args, **kwargs):
        # Si el usuario está autenticado entonces nos direcciona a la url establecida en success_url
        if request.user.is_authenticated():
            return HttpResponseRedirect(self.get_success_url())
        # Sino lo está entonces nos muestra la plantilla del login simplemente
        else:
            return super(Loginusuario, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(Loginusuario, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(Loginusuario, self).get_context_data(**kwargs)
        usuarios = Usuario.objects.all()
        context['datos_user'] = usuarios
        return context

class AddUsuario(CreateView):#Vista para añadir usuarios convencionales
    model = Usuario
    template_name = "login/registro.html"
    form_class = UsuarioForm #form que creamos
    success_url = reverse_lazy('login:login')
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # <proceso el formulario con cleaned data>
            form.save()
            #set_group,valor = Group.objects.get_or_create(name='prueba')
            #actual_user = User.objects.get(username=request.POST.get('username'))
            #actual_user.groups.add(set_group)
            return HttpResponseRedirect(self.success_url)
        return render(request, self.template_name, {'form': form})

class AddUsuarioAdmin(CreateView):#Vista para añadir usuarios convencionales
    model = UsuarioAdmin
    template_name = "adminlio/registro.html"
    form_class = UsuarioForm #form que creamos
    success_url = reverse_lazy('login:login')
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # <proceso el formulario con cleaned data>
            form.save()
            #set_group,valor = Group.objects.get_or_create(name='prueba')
            #actual_user = User.objects.get(username=request.POST.get('username'))
            #actual_user.groups.add(set_group)
            return HttpResponseRedirect(self.success_url)
        return render(request, self.template_name, {'form': form})


######################################################
        #VISTA AJAX PARA LOGIN
#####################################################}
def loginajax(request):
    response_data = dict()
    #username = request.GET.get('username')
    #password = request.GET.get('pwd')
    #stayloggedin = request.GET.get('stayloggedin')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        #login_form = AuthenticationForm(request,request.POST)
        user = authenticate(request, username=username, password=password)
        if user is not None:
            response_data['resultado'] = 'success'
            login(request,user)# nos logeamos super importante para quedar#
            #   autentificados
            response_data['usuario'] = user.username
            #response_data['message'] = 'You"re logged in'
        else:
            response_data['resultado'] = 'failed'
            #response_data['message'] = 'You messed up'

    return JsonResponse({'respuesta':response_data})

def userregajax(request):
    data = dict()
    if request.method =='POST':
        registro = UsuarioForm(request.POST)
        if registro.is_valid():
            registro.save()
            data['resultado'] = 'success'
        else:
            data['resultado'] = 'failed'

    return JsonResponse({'respuesta':data})

templates/plantillas_html/confirm_interface.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
<div id="confirm-nombre">
    <p>NOMBRE DEL PRODUCTO : </p>
    <p id="c-nombre-producto" style="color:#991fff;"></p>
</div>
<br>
<div id="confirm-ubicacion">
    <p>UBICACIÓN : </p>
    <p id="c-ubicacion-producto" style="color:#991fff;"></p>
</div>
<br>
<div id="confirm-precio-producto">
    <p>PRECIO : </p>
    <p id="c-precio-producto" style="color:#991fff;"></p>
</div>
<br>
<div id="confirm-cantidad-producto">
    <p>CANTIDAD : </p>
    <p id="c-cantidad-producto" style="color:#991fff;"></p>
</div>
<br>
<div id="confirm-descripcion-producto">
    <p>DESCRIPCIÓN : </p>
    <p id="c-descripcion-producto" style="color:#991fff;"></p>
</div>

templates/plantillas_html/deletetroquelform.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
        <p>Esta seguro de eliminar troquel?</p>
        <form id="formdeletetroquel"  action="{% url 'adminlio:deletetroqueles' valueid %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <button id="cancel-delete-troquel" type="button">
                <img class="responsive-img" src="{% static 'img/boton_ok.svg' %}">
                <p id="text-cancel-troquel">Cancelar</p>
            </button>
            <button id="delete-troquel-btn" type="submit" value="submit">
                <img class="responsive-img" src="{% static 'img/boton_ok.svg' %}">
                <p id="text-delete-troquel">Borrar</p>
            </button>
        </form>

templates/plantillas_html/edittroquelform.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
         <p style="text-align: center"><span style="position: relative; font-family: shakeoff; background-color: #03f345;color: white; padding: 5px; font-size: 1em;border-radius: 5px">EDITAR TROQUEL</span></p>
        <form id="formedittroquel"  action="{% url 'adminlio:edittroqueles' valueid %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div id="cont-preimg">
                <img id="troquel-edit-previmg" class="responsive-img" src="{% static 'img/emutroquel.png' %}">
            </div>
            <div id="cont-inputslabels-troqueleditform">
                 {{ tformedit.non_field_errors }}

                  {% for hidden_field in tformedit.hidden_fields %}
                    {{ hidden_field.errors }}

                  {% endfor %}

                  <table border="0">
                    {% for field in tformedit.visible_fields %}
                      <tr>
                        <th>{{ field.label_tag }}</th>
                        <td>
                          {{ field.errors }}
                          {{ field }}
                          {{ field.help_text }}
                        </td>
                      </tr>
                    {% endfor %}
                  </table>

            </div>
            <button id="crear-troquel-btn" type="submit" value="submit">
                Aceptar
            </button>
            <button id="cancel-edit-troquel" type="button">
                Cancelar
            </button>
        </form>

templates/plantillas_html/email_content.html
<h1 style=" font-size: 1.5em; line-height: 2em;">Mensaje de usuario.</h1>
<p>Usted ha recibido un nuevo mensaje de un usuario</p>
<dl>
    <dt> Nombre:</dt>
    <dd>{{ name }}</dd>
    <dt> Correo electrónico:</dt>
    <dd>{{  email }}</dd>
    <dt> Mensaje:</dt>
    <dd> {{ message }}</dd>
</dl>

templates/plantillas_html/form_colors.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}




        <form id="formcolors"  action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div id="cont-inputslabels-colorform">
                <div>
                    <p style="text-align: center"><span style="position: relative; font-family: shakeoff; background-color: #03f345;color: white; padding: 5px; font-size: 1.8em">GUARDAR COLOR</span></p>
                </div>
                <div style="background-color: #03f345;color:white;padding: 10px; font-family: shakeoff; border-radius:0 10px 0 10px;">
                    <label for="nombre_c" >NOMBRE:</label>
                    <input id="nombre_c" type="text" name="nombre_color" placeholder="Nombre Color" required>
                </div>
                <br>
                <div style="background-color: #03f345;color:white;padding: 5px; font-family: shakeoff;border-radius:10px 0 10px 0;">
                    <label for="file_c">FILE COLOR:</label>
                    <input id="file_c"  type="file" name="file_color" multiple required>
                </div>
            </div>
            <div id="cont-preimg-color">
                <img id="color-previmg" class="responsive-img" src="{% static 'img/emutroquel.png' %}">
            </div>
            <button id="cancel-add-color" type="button" value="submit">
                Cancelar
            </button>
            <button id="crear-color-btn" type="submit" value="submit">
                Crear
            </button>
        </form>

templates/plantillas_html/form_email.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
<div id="cont-faq-form">
        <p style="color: white;font-size: 2.7vw; padding: 0;">{% trans 'Send your questions!' %}</p>
        <form id="send-emailform"  action="" method="POST">
            {% csrf_token %}

                 {{ tformedit.non_field_errors }}

                  {% for hidden_field in tformedit.hidden_fields %}
                    {{ hidden_field.errors }}
                    {{ hidden_field }}
                  {% endfor %}
                  <div id="contact-table">
                      <div class="row-login-form">
                           <div class="column2left">
                                <label for="nombre_email" >{% trans 'Name' %}</label>
                           </div>
                           <div class="column2right">
                               <input id="nombre_email"  class="input-contact" type="text" name="name_email" placeholder="" required>
                           </div>
                      </div>
                      <div class="row-login-form">
                          <div class="column2left">
                            <label for="email_address" >{% trans 'Email' %}</label>
                          </div>
                          <div class="column2right">
                              <input id="email_address"  class="input-contact" type="text" name="email_addr" placeholder="" required>
                          </div>
                      </div>
                      <div class="row-login-form">
                          <div class="column2left">
                            <label for="email_message" >{% trans 'Email message:' %}</label>
                          </div>
                          <div class="column2right">
                              <textarea  class="input-contact" style="resize: none;" id="email_message"  name="email_msg" required> </textarea>
                          </div>
                      </div>
                  </div>

            <button id="send-faq" type="submit">
                <img style="width:100%; height: auto;position: absolute; top: 0;left: 0;" src="{% static 'img/png/productos/botones/boton_comprar.svg' %}">
                <p class="send-email-text">{% trans 'Send!' %}</p>
            </button>

        </form>
</div>

templates/plantillas_html/form_findtroquel.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
            <div id="cont-troquelfindform">

                <div>
                    <label for="nombre_t" >Nombre:</label>
                    <input id="nombre_t" type="text" name="nombre_troquel" placeholder="Nombre Troquel" required>
                    <label for="size_t">Size Troquel</label>
                    <input id="size_t"  type="number" name="size_troquel">
                    <label for="category-tfind">Categoría Troquel</label>
                    <select id="category-tfind"  name="categoria_troquel">
                        {% for x,y in choices_type.categoria_troquel.field.choices %}
                           <option value="{{ x }}">{{ y }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <button id="find-troquel-btn" type="button" value="submit">
                <img class="responsive-img" src="{% static 'img/boton_ok.svg' %}">
                <p id="text-find-troquel">Buscar!</p>
            </button>

templates/plantillas_html/form_productos.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
<form id="create_product_form" action="" method="post" onsubmit="return validate_productform()" enctype="multipart/form-data">{% csrf_token %}
            <div>{{ form.as_p }}</div>

            <table class="table">
                {{ crearzona.management_form }}

                {% for form in crearzona.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th>{{ field.label|capfirst }}</th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="{% cycle row1 row2 %} formset_row">
                        {% for field in form.visible_fields %}
                            <td>
                                {# Include the hidden fields in the form #}
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {{ field }}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <!--<div>
                <input id="show-patterns" type="checkbox">
            </div>-->
            <div id="cont-info-troquel">
                <object id="zonas-info-troquel"  data="" type="image/svg+xml"></object>
            </div>
            <!--
            <div id="cont-editzones">
                <table id="edit-zone-table">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Color</th>
                            <th>Imagen</th>
                            <th>Change</th>
                        </tr>
                    </thead>
                    <tbody id="tbody-zone">
                    <tr>
                        <th>hola</th>
                    </tr>
                    </tbody>
                </table>
            </div>
            <input id="change-selects" type="button" value="Change"/>-->
            <input id="saveproducto" style="opacity: 0;" type="submit" value="Save"/>
        </form>

templates/plantillas_html/login-form.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
{% load socialaccount %}
{% providers_media_js %}
<form id="ajax-login-form" action="" method="POST">
            {% csrf_token %}
            <!-- Mostrando errores en formulario-->
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            <!-- Fin errores formulario-->
                <div class="cont-log-reg-data">
                    <div class="row-login-form">
                        <div class="column2left"><!-- 2 columnas por fila-->
                            <label for="username">{% trans "User or email"%} <span class="req">*</span>
                            </label>
                        </div>
                        <div class="column2right">
                            <input class="inputs-login" id="username" type="text" required autocomplete="off" name="username">
                        </div>
                    </div>
                    <div class="row-login-form">
                        <div class="column2left">
                            <label for="password">{% trans "Password"%}<span class="req">*</span>
                            </label>
                        </div>
                        <div class="column2right">
                            <input id="password" class="inputs-login" type="password" required autocomplete="off" name="password">
                        </div>
                    </div>
                    <br>
                    <div class="row-login-form">
                        <div class="column2left">
                            <p style="font-size: 0.8em;">{% trans "Don't have account?" %}  <span id="go2reg" style="padding: 3px;border-radius:3px;background-color: white;color: #31acf7;-webkit-touch-callout: none;-khtml-user-select: none;-moz-user-select: none;-ms-user-select: none;user-select: none;">{% trans 'Sign Up here!' %}</span></p>
                        </div>
                        <div class="column2right">

                        </div>
                    </div>
                     <br>
                    <div class="row-login-form">
                        <div class="column2left">
                            <p style="font-size: 0.8em;"><a style="padding: 3px;border-radius:3px;background-color: white;color: #31acf7;-webkit-touch-callout: none;-khtml-user-select: none;-moz-user-select: none;-ms-user-select: none;user-select: none;" href="{% url 'password_reset' %}">{% trans "Forgot Password?"%}</a></p>
                        </div>
                        <div class="column2right">

                            <a href="{% provider_login_url "facebook" method="js_sdk" %}"><img style="width: 80%; height: auto;" src="{% static 'img/facelog.png' %}"></a>
                        </div>
                    </div>
                     <br>
                    <div class="row-login-form">
                        <div class="column2left">
                            <input style="padding: 5px;border-radius: 5px;color: #31acf7;background-color: white" type="submit" value="{% trans 'Log In' %}">
                        </div>
                        <div class="column2right">

                        </div>
                    </div>

                </div>
          {% comment %}<p class="forgot"><a href="{% url 'password_reset' %}">{% trans "Forgot Password?"%}</a></p>{% endcomment %}
</form>

templates/plantillas_html/user-panel.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}

<ul class="user-profile">
    <li>
        <p style="text-align: Left">Bienvenido <span id="name-profile">{{ transfer }}</span></p>
    </li>
    <li>
        <a class="btn-mob-salir simple-link font-white" href="{% url 'salirhome' %}">Salir</a>
    </li>
</ul>

templates/plantillas_html/userlogin.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
    <div class="user-access-btns">
        <div class="third-column-flex"></div>
        <div  class="third-column-flex"><span class="login-btn">Login </span><span class="reg-btn"> LogUp</span></div>
        <div class="third-column-flex">
            <a id="btn-loginadmin" href="{% url 'adminlio:loginadmin' %}">Login Admin</a>
        </div>
    </div>