login/urls.py
from django.conf.urls import url
from django.contrib import admin

from sys import path
from django.conf.urls import url,include
from django.contrib import admin
from login.views import Loginusuario, AddUsuario
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import javascript_catalog
from django.contrib.auth.views import logout

js_info_dict = {
    #domain is default
    'packages': ('login',),
}
urlpatterns = [
    url(r'^$', Loginusuario.as_view(), name="login"),
    url(r'^registro/', AddUsuario.as_view(), name='registro'),
    url(r'^salir$', logout, name="salir", kwargs={'next_page': 'login:login'})
]

madebylio/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from base.views import home,showproducts
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import javascript_catalog
from django.contrib.staticfiles.urls import static
from adminlio.views import showimagenes,showpost
from login.views import loginajax,userregajax
from base.views import send_mail,findprodforcategory,savebuy,retrieve_data,fillmobileshopcar,validate_username,cleancookies,savecanvasimage,chargecolors,showsameproducts,test_query,hometeste
from adminlio.views import validate_troquel
from django.contrib.auth.views import logout
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm,password_reset_complete

js_info_dict = {
    #domain is default
    'packages': ('base',),
}
urlpatterns = [

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
        url(_(r'^admin/'), admin.site.urls),
        url(_(r'^login/'), include('login.urls', namespace='login')),
        url(_(r'^adminlio/'), include('adminlio.urls', namespace='adminlio')),
        url(_(r'^pagos/'), include('pagos.urls', namespace='pagos')),
        url(_(r'^$'), home,name='home'),
        url(_(r'^teste'), hometeste,name='hometeste'),
        #url(_(r'^oauth/'), include('social_django.urls', namespace='social')),  # <-- social auth
        url(_(r'accounts/'),include('allauth.urls')),
        url(_(r'^cleancookies$'), cleancookies,name='cleancookies'),
        url(_(r'^showsameproducts$'), showsameproducts,name='showsameproducts'),
        url(_(r'chargecolors$'), chargecolors,name='chargecolors'),
        url(_(r'^savecanvas$'), savecanvasimage,name='savecanvas'),
        url(_(r'^savebuy$'), savebuy,name='savebuy'),
        url(_(r'^testquery$'), test_query,name='testquery'),
        url(_(r'^fillmobileshopcar$'), fillmobileshopcar,name='fillmobileshopcar'),
        url(_(r'^pagos/retrieve_data$'), savebuy,name='retrieve_data'),
        url(r'^send-mail$',send_mail , name="send-mail"),       
        url(r'^loginuser$', loginajax, name="loginuser"),
        url(r'^reguser$', userregajax, name="reguser"),
        url(_(r'^showproducts$'), showproducts,name='showproducts'),
        url(_(r'^validateusername$'), validate_username,name='validateusername'),
        url(_(r'^showimagenes$'),showimagenes, name="showimages"),
        url(_(r'^showgalleries$'),showpost, name="showgalleries"),
        url(_(r'^showprodforcategories'),findprodforcategory,name='showprodforcategories'),
        url(_(r'^salir$'), logout, name="salirhome", kwargs={'next_page': 'home'}),
        #url para recuperar contraseña
        url(_(r'^reset/password_reset/$'),password_reset,{'template_name':'registration/password_reset_form.html','email_template_name':'registration/password_reset_email.html'},name='password_reset'),
                url(_(r'^reset/password_reset_done/$'),password_reset_done,{'template_name':'registration/password_reset_done.html'},name='password_reset_done'),
                url(_(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$'),password_reset_confirm, {'template_name':'registration/password_reset_confirm.html'},name='password_reset_confirm'),
                url(_(r'^reset/done/$'),password_reset_complete,{'template_name':'registration/password_reset_complete.html'},name="password_reset_complete"),
        url(r'^i18n/',include('django.conf.urls.i18n')),
        url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),
)

pagos/urls.py
from django.conf.urls import url
from django.contrib import admin

from sys import path
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import javascript_catalog
from django.contrib.auth.views import logout
from .views import create_order,CrearZona,returninfoprod,epaycotest,epaycoresponse,epaycoconfirmacion
js_info_dict = {
    #domain is default
    'packages': ('pagos',),
}
urlpatterns = [
    url(r'^$', CrearZona.as_view(), name="compra"),
    url(r'^epaycotest',epaycotest,name="epaycotest"),
    url(r'^epaycoresponse',epaycoresponse,name='response'),
    url(r'^epaycoconfirmacion',epaycoconfirmacion,name='confirmation'),
    url(r'^returninfoprod', returninfoprod, name="returninfoprod"),
]

pagos/models.py
from django.db import models
from adminlio.models import Producto
from login.models import Usuario
from django.contrib.auth.models import User
# Create your models here.
class Factura(models.Model): #sera en si el compilado de una compra con uno o varios productos
    usuario_factura = models.ForeignKey(User, on_delete=models.CASCADE)
    nombre_factura = models.CharField(max_length=40)
    fecha_factura = models.DateTimeField(auto_now_add=True, blank=True)
    def __str__(self):
        return "%s" % self.nombre_factura

class Item(models.Model):
    producto_item = models.ForeignKey(Producto,on_delete = models.CASCADE)
    factura_item = models.ForeignKey(Factura,on_delete = models.CASCADE)
    cantidad_item = models.IntegerField()

pagos/forms.py
from .models import Item,Factura
from django import forms
from django.forms.models import inlineformset_factory,formset_factory
class FacturaForm(forms.ModelForm):
    class Meta:
        model = Factura
        fields = ['nombre_factura']
        exclude =['usuario_factura','fecha_factura']

class ItemForm(forms.ModelForm):
    show_price_producto = forms.CharField()
    tamaño_producto = forms.CharField()
    class Meta:
        model = Item
        fields = ['producto_item','cantidad_item']

#ItemFormSet = inlineformset_factory(Factura,Item,
#form=ItemForm,extra=3,max_num=6,can_delete=False)


#ASI DEBEMOS ENVIARLE LOS DATOS A EL FORMSET PARA PODER HACER LA COMPRA
#data = [{'producto_item':9,'cantidad_item':2},{'producto_item':6,'cantidad_item':3}]
# DE ESA MANERA PODEMOS CARGAR EL FORSET ASI
#detalle_compra_form_set = ItemFormSet(initial=data)
#Y LO RENDERIZAMOS Y SALE
#COMO ? EN ESTA PAGINA APARECE http://pythonpiura.org/posts/modificacion-de-datos-con-django-formset/

#detalle_compra_form_set = ItemFormSet(initial=detalles_data)

pagos/views.py
from django.shortcuts import render
from .models import Item,Factura
from .forms import ItemForm,FacturaForm#,ItemFormSet
from django.forms.models import inlineformset_factory,formset_factory
from django.views.generic import View,TemplateView, CreateView, UpdateView, FormView,DeleteView, ListView
from adminlio.models import Producto
from django.shortcuts import render, render_to_response,redirect,HttpResponse,HttpResponseRedirect
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, JsonResponse,HttpResponse
from django.db import transaction
from django.contrib.auth.models import User
from login.models import Usuario
import _pickle as cPickle
import json
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder
from django.template.loader import render_to_string
# Create your views here.
def create_order(request):

    if request.method == 'POST':

        factura = FacturaForm(request.POST)
        if factura.is_valid():
            factura.save()

        itemFormSet = formset_factory(ItemForm)
        item_formset = itemFormSet(request.POST)

        if item_formset.is_valid():
            for algo in item_formset:
                pass#new_orders = []
            #for order_form in item_formset:
            #    new_order = Item(
            #         Factura,
            #    )
            #    new_orders.append(new_order)

            #Item.objects.bulk_create(new_orders)
            item_formset.save()



    if request.method == 'GET':

       factura_form = FacturaForm()

       ItemFormSet = formset_factory(ItemForm, extra=2)
       item_formset = ItemFormSet()

       template_context = {
           'factura_form': factura_form,
           'item_formset': item_formset,
           }

       template = 'pagos/index.html'

       return render(request, template, template_context)


class CrearZona(CreateView):
    success_url = reverse_lazy("pagos:epaycotest")
    model = Factura
    template_name = 'pagos/index.html'
    fields = ['nombre_factura']
    peticion = dict()
    #success_url = reverse_lazy('home')
    def get_context_data(self, **kwargs):
        data = super(CrearZona, self).get_context_data(**kwargs)

        if self.request.POST:
            ItemFormSet = inlineformset_factory(Factura, Item,
                                                form=ItemForm)
            data['crearzona'] = ItemFormSet(self.request.POST)
            self.peticion = self.request.POST
        else:
            datos_compra = self.request.session['datacompra']
            #dataaa = [[9, 1200], [16, 12]]
            compra = [dict(zip(['producto_item','cantidad_item','show_price_producto','tamaño_producto'], alumno)) for alumno in datos_compra]
            ItemFormSet = inlineformset_factory(Factura, Item,
                                                form=ItemForm, extra=len(compra), can_delete=False)
            data['crearzona'] = ItemFormSet(initial=compra)
            data['cookiet'] = len(self.request.session['datacompra'])
            data['usuario'] = self.request.user
            #usuario = self.request.user
            #queryset = Usuario.objects.filter(username__icontains=usuario)
            #self.my_object = get_object_or_404(queryset)
            #data['userinfo'] = self.my_object#enviando mas de un dato al template
        return data

    def form_valid(self, form):
        context = self.get_context_data()

        #form.instance.user = self.request.user #obtenemos el user
        zonas = context['crearzona']
        with transaction.atomic(): #CREAMOS COMUNICACION ASINCRONA CON LA BASE DE DATOS
            #self.object = form.save(commit=False)
            #self.object.usuario_factura = User.objects.get(username=self.request.user)
            #self.object.save()

            if zonas.is_valid(): #VERICAMOS QUE LOS CAMPOS DEL FORMULARIOS para los inline formsets
                zonas.instance = self.object


            #print(crearzonas)
            fake_zonas = zonas.cleaned_data # diccionario con los datos para llenar el formulario
            #print(zonas.cleaned_data)
            for zone in fake_zonas:
                fact_producto = Producto.objects.get(nombre_producto=zone['producto_item'])
                zone['producto_item'] = fact_producto.id #las sessiones no aceptan objetos query por eso le damos directamente el id usando un busqueda en la base datos
                zone['factura_item'] = '' # valor vacio porque tambien es un query object

            #ItemFormSeta = inlineformset_factory(Factura, Item, form=ItemForm, extra=1, can_delete=False)
            #crearzonas = ItemFormSeta(initial=fake_zonas)

            #print(fake_zonas)
                #zonas.save()
                #print(zonas)
            #print(fake_zonas)


            #algo = render_to_string(zonas)

            self.request.session['inline'] = fake_zonas
            #print(self.request.session.get('inline'))
            self.request.session['form'] = form.cleaned_data
            #print(form)

            #ENVIAMOS EL VALOR TOTAL DE LA TRANSACCION
            self.request.session['val_total'] = self.request.POST.get('total-compra')
            self.request.session['cambio'] = self.request.POST.get('input-cambio')
            #print(val_total)

            #print(zonas.cleaned_data[0]['producto_item'])
        #return super(CrearZona, self).form_valid(form)
        return redirect('pagos:epaycotest') # redireccionamos a nuestra app de compras epayco

def returninfoprod(request):
    data = dict()
    if request.method == 'GET':
        if request.is_ajax():
            id_produc  = request.GET.get('id_producto')
            producto = Producto.objects.get(pk=id_produc).precio_producto
            data['producto'] = producto
    return JsonResponse({'datos':data})

def epaycotest(request):
    #ItemFormSet = inlineformset_factory(Factura, Item,
                                        #form=ItemForm, extra=len(request.session['inline']), can_delete=False)
    #form = FacturaForm(request.session['form'])
    #crearzona = ItemFormSet(initial=request.session['inline'])
    total = request.session['val_total']
    cambio = request.session['cambio']
    return render(request, 'pagos/epayco.html',{'total':total,'cambio':cambio})


def epaycoresponse(request):
    form = ''
    crearzona = ''
    ItemFormSet = inlineformset_factory(Factura, Item,
                                        form=ItemForm, extra=len(request.session['inline']), can_delete=False)
    if request.method == 'GET':

        form = FacturaForm(request.session['form'])
        crearzona = ItemFormSet(initial=request.session['inline'])
    else:
        factura = FacturaForm(request.POST)
        items = ItemFormSet(request.POST)
        with transaction.atomic():
            f_instance = factura.save(commit=False)
            f_instance.usuario_factura = User.objects.get(username=request.user)
            f_instance.save()
            if items.is_valid():
                items.instance = f_instance
                items.save()
            #actualizamos stock
            productos = items.cleaned_data

            for zone in productos:
                fact_producto = Producto.objects.get(nombre_producto=zone['producto_item'])
                fact_producto.cantidad_producto = fact_producto.cantidad_producto - zone['cantidad_item']#las sessiones no aceptan objetos query por eso le damos directamente el id usando un busqueda en la base datos
                fact_producto.save()


            form = FacturaForm()
            crearzona = ItemFormSet()

        del request.session['datacompra']  # borramos nuestra session de compra porque ya compramos!
        return render(request, 'pagos/epaycoconfirmation.html', {'form': form, 'crearzona': crearzona})

    return render(request,'pagos/epaycoresponse.html', {'form': form, 'crearzona': crearzona})

def epaycoconfirmacion(request):
    form = ''
    crearzona = ''
    ItemFormSet = inlineformset_factory(Factura, Item,
                                        form=ItemForm, extra=len(request.session['inline']), can_delete=False)
    if request.method == 'GET':


        form = FacturaForm(request.session['form'])
        crearzona = ItemFormSet(initial=request.session['inline'])
    else:
        factura = FacturaForm(request.POST)
        items = ItemFormSet(request.POST)
        with transaction.atomic():
            f_instance = factura.save(commit=False)
            f_instance.usuario_factura = User.objects.get(username=request.user)
            f_instance.save()
            if items.is_valid():
                items.instance = f_instance
                items.save()
            form = FacturaForm()
            crearzona = ItemFormSet()

        del request.session['datacompra']  # borramos nuestra session de compra porque ya compramos!
        return redirect('home')



    return render(request, 'pagos/epaycoconfirmation.html', {'form': form, 'crearzona': crearzona})

templates/pagos/epaycoconfirmation.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    transaccion exitosa!!!
</body>
</html>

templates/pagos/epaycoresponse.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <meta charset="utf-8">
                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
                <title>Formulario Pruebas Respuesta</title>
                <!-- Bootstrap -->
                <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
                <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
                <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
                <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
                <!--[if lt IE 9]>
                      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
                      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
                    <![endif]-->
</head>
<body>
     <header id="main-header" style="margin-top:20px">
                    <div class="row">
                        <div class="col-lg-12 franja">
                            <img class="center-block" src="https://369969691f476073508a-60bf0867add971908d4f26a64519c2aa.ssl.cf5.rackcdn.com/btns/epayco/logo1.png" style="">
                        </div>
                    </div>
                </header>
                <div class="container">
                    <div class="row" style="margin-top:20px">
                        <div class="col-lg-8 col-lg-offset-2 ">
                            <h4 style="text-align:left"> Respuesta de la Transacción </h4>
                            <hr>
                        </div>
                        <div class="col-lg-8 col-lg-offset-2 ">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <tbody>
                                        <tr>
                                            <td>Referencia</td>
                                            <td id="referencia"></td>
                                        </tr>
                                        <tr>
                                            <td class="bold">Fecha</td>
                                            <td id="fecha" class=""></td>
                                        </tr>
                                        <tr>
                                            <td>Respuesta</td>
                                            <td id="respuesta"></td>
                                        </tr>
                                        <tr>
                                            <td>Motivo</td>
                                            <td id="motivo"></td>
                                        </tr>
                                        <tr>
                                            <td class="bold">Banco</td>
                                            <td class="" id="banco">
                                        </tr>
                                        <tr>
                                            <td class="bold">Recibo</td>
                                            <td id="recibo"></td>
                                        </tr>
                                        <tr>
                                            <td class="bold">Total</td>
                                            <td class="" id="total">
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
     <!-- FORM OCULTO QUE GUARDA NUESTRA INFORMACION-->
                <form  id="saveallshop" action="{% url 'pagos:response' %}" method="post" style="border-radius:10px; background-color: #ececec;padding: 20px; position: absolute; left:100%;top:100%;opacity: 0;">
    {% csrf_token %}

        {{ crearzona.management_form }}

        {{ form }}
       <br>


    <br>
    <br>
    <table>
    {% for form in crearzona%}
        <tr>
            {% for field in form.visible_fields %}
                <td>
                    {{ field.name }}
                </td>
                <td>
                    {{ field.as_widget }}
                </td>
            {% endfor %}
                <td>
                    <button class="btn-delete-compra" type="button" style="background-color: red; color: white;border-radius: 3px;padding: 5px;border:none">delete</button>
                </td>
        </tr>

    {% endfor %}
    </table>
        <!--{% for yum in crearzona %}
             {{ yum.as_ul }}
        {% endfor %}-->
    <br>
    <div id="total-compra"></div>
    <button id="add-compra-producto" type="button" style="background-color: #30defc; color: white;border-radius: 3px;padding: 5px;border:none">Add product</button>
    <a id="cancel-compra-producto" href="{% url 'home' %}" style="background-color: #30defc; color: white;border-radius: 3px;padding: 5px;border:none;text-decoration: none;">Cancelar compra</a>
        <input id='btn-submit-compra' type="submit" value="Aceptar" style="background-color: #fc20c1; color: white;border-radius: 3px;padding: 5px;border:none" />
</form>
                <footer>
                    <div class="row">
                        <div class="container">
                            <div class="col-lg-8 col-lg-offset-2">
                                <img src="https://369969691f476073508a-60bf0867add971908d4f26a64519c2aa.ssl.cf5.rackcdn.com/btns/epayco/pagos_procesados_por_epayco_260px.png" style="margin-top:10px; float:left"> <img src="https://369969691f476073508a-60bf0867add971908d4f26a64519c2aa.ssl.cf5.rackcdn.com/btns/epayco/credibancologo.png" height="40px" style="margin-top:10px; float:right">
                            </div>
                        </div>
                    </div>
                </footer>
                <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.js"></script>
                <!-- Include all compiled plugins (below), or include individual files as needed -->
                <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
                <script>
                function getQueryParam(param) {
                    location.search.substr(1)
                        .split("&")
                        .some(function(item) { // returns first occurence and stops
                            return item.split("=")[0] == param && (param = item.split("=")[1])
                        })
                    return param
                }
                $(document).ready(function() {
                    //llave publica del comercio

                    //Referencia de payco que viene por url
                    var ref_payco = getQueryParam('ref_payco');
                    //Url Rest Metodo get, se pasa la llave y la ref_payco como paremetro
                    var urlapp = "https://api.secure.payco.co/validation/v1/reference/" + ref_payco;

                    $.get(urlapp, function(response) {


                        if (response.success) {

                            if (response.data.x_cod_response == 1) {
                                //Codigo personalizado

                                alert("Transaccion Aprobada");
                                $('#saveallshop').submit();

                                console.log('transacción aceptada');
                            }
                            //Transaccion Rechazada
                            if (response.data.x_cod_response == 2) {
                                console.log('transacción rechazada');
                            }
                            //Transaccion Pendiente
                            if (response.data.x_cod_response == 3) {
                                console.log('transacción pendiente');
                            }
                            //Transaccion Fallida
                            if (response.data.x_cod_response == 4) {
                                console.log('transacción fallida');
                            }

                            $('#fecha').html(response.data.x_transaction_date);
                            $('#respuesta').html(response.data.x_response);
                            $('#referencia').text(response.data.x_id_invoice);
                            $('#motivo').text(response.data.x_response_reason_text);
                            $('#recibo').text(response.data.x_transaction_id);
                            $('#banco').text(response.data.x_bank_name);
                            $('#autorizacion').text(response.data.x_approval_code);
                            $('#total').text(response.data.x_amount + ' ' + response.data.x_currency_code);


                        } else {
                            alert("Error consultando la información");
                        }
                    });

                });
                </script>
</body>
</html>

templates/pagos/index.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pagos</title>
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/productos.css' %}">
    <style>
        @font-face
        {
            font-family: shakeoffchunki;
            src: url('{% static 'fonts/KGShakeitOffChunky.ttf' %}');
        }

        @font-face
        {
            font-family: BROMO;
            src: url('{% static 'fonts/BROMO.otf' %}');
        }

        @font-face
        {
            font-family: shakeoff;
            src: url('{% static 'fonts/KGShakeitOff.ttf' %}');
        }
        span#title-voice
        {
            font-family: shakeoff;
            font-size: 1em;
            color:white;
            border-radius: 5px;
            background-color: #1bf70c;
            padding: 5px;
            width: auto;
        }
        td input[type=text],td input[type=number]
        {
            width: 50px;
        }
        .show-price-producto
        {
            padding-left: 30px;
            padding-right: 30px;
        }
    </style>
    <script type="text/javascript" src="{% static 'js/productos.js' %}"></script>
</head>
<body>
<div id="cont-tabla-compras" style="width: 90%; position: absolute; left: 5%;">
    <h1><span id="title-voice">Factura de compra!</span></h1>
    <form  action="{% url 'pagos:compra' %}" method="post" style="border-radius:10px; background-color: #ececec;padding: 20px;">
    {% csrf_token %}

        {{ crearzona.management_form }}

        {{ form }}
       <br>

    <!--{{ crearzona.as_table }}-->
    <br>
    <br>
    <table>
    {% for form in crearzona%}
        <tr>
            {% for field in form.visible_fields %}
                {% if  "show_price_producto" in field.name or "tamaño_producto" in field.name%}

                    <td>
                    {{ field.name }}
                    </td>
                    <td class="show-price-producto">
                        {{ field.value }}
                    <input type="hidden" id="{{ field.id_for_label }}" name="{{ field.html_name }}" value="{{ field.value }}">
                    </td>
                {% else %}
                    <td>
                    {{ field.name }}
                    </td>
                    <td>
                        {{ field.as_widget }}
                    </td>
                {% endif %}

            {% endfor %}
                <td>
                    <button class="btn-delete-compra" type="button" style="background-color: red; color: white;border-radius: 3px;padding: 5px;border:none">delete</button>
                </td>
        </tr>

    {% endfor %}
    </table>
        <!--{% for yum in crearzona %}
             {{ yum.as_ul }}
        {% endfor %}-->
    <br>
    <div >
        <label id="total-compra"></label>
        <input id="input-total-compra" name="total-compra" type="hidden">
        <input id="input-cambio" name="input-cambio" type="hidden">
        <script type="text/javascript">
            var cambio = getCookie('cambio');
            if(cambio === 'AUD' || cambio === 'USD' || cambio === 'Euro')
            {
                cambio = 'usd';
            }
            else
            {
                cambio = 'cop';
            }
            document.querySelector('#input-cambio').value = cambio;
        </script>
    </div>
    <button id="add-compra-producto" type="button" style="background-color: #30defc; color: white;border-radius: 3px;padding: 5px;border:none">Add product</button>
    <a id="cancel-compra-producto" href="{% url 'home' %}" style="background-color: #30defc; color: white;border-radius: 3px;padding: 5px;border:none;text-decoration: none;">Cancelar compra</a>
        <input id='btn-submit-compra' type="submit" value="Aceptar" style="background-color: #fc20c1; color: white;border-radius: 3px;padding: 5px;border:none" />
</form>
</div>


<script type="text/javascript" src="{% static 'js/indexpagos.js' %}"></script>
</body>
</html>