adminlio/urls.py
from django.conf.urls import url
from django.contrib import admin

from sys import path
from django.conf.urls import url,include
from django.contrib import admin
from login.views import LoginAdmin
from adminlio.views import adminhome,savetroquel,findtroqueles,edittroqueles,deletetroqueles,updatetroquel,addcolor,getcolores,CreateGallery,showpost,showimagenes,Listaproductos,getzonesforproduct,EditarProducto,EliminarProducto,repeattroquel,EditGallery,Listagalerias,EliminarGaleria,validate_troquel
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import javascript_catalog
from django.contrib.auth.views import logout


js_info_dict = {
    #domain is default
    'packages': ('adminlio',),
}
urlpatterns = [
    url(r'^$', adminhome.as_view(), name="homeadmin"),
    url(r'^login$', LoginAdmin.as_view(), name="loginadmin"),
    url(r'^savetroquel$',savetroquel , name="savetroquel"),
    url(r'^repeattroquel$',repeattroquel , name="repeattroquel"),
    url(r'^findtroquel$',findtroqueles , name="findtroquel"),
    url(r'^updatetroquel$',updatetroquel , name="updatetroquel"),
    url(r'^creategallery',CreateGallery.as_view() , name="creategallery"),
    url(r'^editgallery/(?P<pk>\d+)$',EditGallery.as_view() , name="editgallery"),
    url(r'^listgallery',Listagalerias , name="listgallery"),
    url(r'^deletegallery/(?P<pk>\d+)$',EliminarGaleria.as_view() , name="deletegallery"),
    url(r'^getcolores$',getcolores, name="getcolores"),
    url(r'^addcolor$',addcolor , name="addcolor"),
    url(r'^edittroqueles/(?P<pk>\d+)$',edittroqueles , name="edittroqueles"),
    url(r'^deletetroqueles/(?P<pk>\d+)$',deletetroqueles , name="deletetroqueles"),
    url(r'^editarproducto/(?P<pk>\d+)$',EditarProducto.as_view(),name="editarproducto"),
    url(r'^elmininarproducto/(?P<pk>\d+)$',EliminarProducto.as_view(),name="eliminarproducto"),

    url(r'^validatetroquel$', validate_troquel, name="validatetroquel"),

    url(r'^listproductos',Listaproductos,name='listproductos'),
    url(r'^zonas$', getzonesforproduct, name="zonas"),
    #url(r'^registro/', AddAdmin.as_view(), name='registroadmin'),
    url(r'^salir$', logout, name="salir", kwargs={'next_page': 'adminlio:loginadmin'})
]

login/urls.py
from django.conf.urls import url
from django.contrib import admin

from sys import path
from django.conf.urls import url,include
from django.contrib import admin
from login.views import Loginusuario, AddUsuario
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import javascript_catalog
from django.contrib.auth.views import logout

js_info_dict = {
    #domain is default
    'packages': ('login',),
}
urlpatterns = [
    url(r'^$', Loginusuario.as_view(), name="login"),
    url(r'^registro/', AddUsuario.as_view(), name='registro'),
    url(r'^salir$', logout, name="salir", kwargs={'next_page': 'login:login'})
]

madebylio/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from base.views import home,showproducts
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import javascript_catalog
from django.contrib.staticfiles.urls import static
from adminlio.views import showimagenes,showpost
from login.views import loginajax,userregajax
from base.views import send_mail,findprodforcategory,savebuy,retrieve_data,fillmobileshopcar,validate_username,cleancookies,savecanvasimage,chargecolors,showsameproducts,test_query,hometeste
from adminlio.views import validate_troquel
from django.contrib.auth.views import logout
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm,password_reset_complete

js_info_dict = {
    #domain is default
    'packages': ('base',),
}
urlpatterns = [

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
        url(_(r'^admin/'), admin.site.urls),
        url(_(r'^login/'), include('login.urls', namespace='login')),
        url(_(r'^adminlio/'), include('adminlio.urls', namespace='adminlio')),
        url(_(r'^pagos/'), include('pagos.urls', namespace='pagos')),
        url(_(r'^$'), home,name='home'),
        url(_(r'^teste'), hometeste,name='hometeste'),
        #url(_(r'^oauth/'), include('social_django.urls', namespace='social')),  # <-- social auth
        url(_(r'accounts/'),include('allauth.urls')),
        url(_(r'^cleancookies$'), cleancookies,name='cleancookies'),
        url(_(r'^showsameproducts$'), showsameproducts,name='showsameproducts'),
        url(_(r'chargecolors$'), chargecolors,name='chargecolors'),
        url(_(r'^savecanvas$'), savecanvasimage,name='savecanvas'),
        url(_(r'^savebuy$'), savebuy,name='savebuy'),
        url(_(r'^testquery$'), test_query,name='testquery'),
        url(_(r'^fillmobileshopcar$'), fillmobileshopcar,name='fillmobileshopcar'),
        url(_(r'^pagos/retrieve_data$'), savebuy,name='retrieve_data'),
        url(r'^send-mail$',send_mail , name="send-mail"),       
        url(r'^loginuser$', loginajax, name="loginuser"),
        url(r'^reguser$', userregajax, name="reguser"),
        url(_(r'^showproducts$'), showproducts,name='showproducts'),
        url(_(r'^validateusername$'), validate_username,name='validateusername'),
        url(_(r'^showimagenes$'),showimagenes, name="showimages"),
        url(_(r'^showgalleries$'),showpost, name="showgalleries"),
        url(_(r'^showprodforcategories'),findprodforcategory,name='showprodforcategories'),
        url(_(r'^salir$'), logout, name="salirhome", kwargs={'next_page': 'home'}),
        #url para recuperar contraseña
        url(_(r'^reset/password_reset/$'),password_reset,{'template_name':'registration/password_reset_form.html','email_template_name':'registration/password_reset_email.html'},name='password_reset'),
                url(_(r'^reset/password_reset_done/$'),password_reset_done,{'template_name':'registration/password_reset_done.html'},name='password_reset_done'),
                url(_(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$'),password_reset_confirm, {'template_name':'registration/password_reset_confirm.html'},name='password_reset_confirm'),
                url(_(r'^reset/done/$'),password_reset_complete,{'template_name':'registration/password_reset_complete.html'},name="password_reset_complete"),
        url(r'^i18n/',include('django.conf.urls.i18n')),
        url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),
)

galeria/models.py
from django.db import models

# Create your models here.
from django.utils.text import slugify
# Create your models here.
class Postgallery(models.Model):
    title = models.CharField(max_length=128)
    body = models.CharField(max_length=400)
    def __str__(self):
        return "%s" % self.title

def get_image_filename(instance, filename):
    title = instance.post.title
    slug = slugify(title)
    return "post_images/%s-%s" % (slug, filename)


class Imagegallery(models.Model):
    post = models.ForeignKey(Postgallery, default=None,on_delete = models.CASCADE)
    image = models.ImageField(upload_to=get_image_filename,
                              verbose_name='Image')
    def __str__(self):
        return "%s" % self.image

galeria/forms.py
from django.forms import ModelForm, inlineformset_factory
from .models import Postgallery,Imagegallery
from django import forms
from django.forms.models import inlineformset_factory,modelformset_factory
from django.contrib.auth.forms import UserCreationForm

class PostForm(forms.ModelForm):
    title = forms.CharField(max_length=128)
    body = forms.CharField(max_length=245, label="Item Description.")

    class Meta:
        model = Postgallery
        fields = ('title', 'body', )


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image',required=True)
    class Meta:
        model = Imagegallery
        fields = ('image', )

GalleryFormSet = inlineformset_factory(Postgallery,Imagegallery,
form=ImageForm,extra=1,can_delete=False,min_num=1,validate_min=True,max_num=1)

galeria/views.py
from django.shortcuts import render

# Create your views here.

templates/galeria/edit_galeria.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>lio admin</title>
    <link rel="stylesheet" href="{% static 'css/adminlio.css' %}" type="text/css">
    <script>
         var static_url = "{% get_static_prefix %}";
        var media_url = "{% get_media_prefix %}";
        var juipo = 'probando';
    </script>
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>

</head>
<body>
<h1 style="bacñkground-color: #0acc54;padding: 10px;border-radius: 10px 0 10px 0;color:white;">Create Gallery</h1>
<div style="position: absolute; left: 40%;top: 27.5%; width: 35%; height: 70%; background-color: #00A6D8; overflow-y: scroll;">
    <form id="post_form" method="post" action="" enctype="multipart/form-data">

    {% csrf_token %}
    {{ form.as_p }}
    <!--{% for field in postForm %}
        {{ field }} <br />
                    {% endfor %} -->

    {{ editgaleria.management_form }}
    <table id="aditional-items">
       {% for field in editgaleria %}
        <tr><td>{{ field }}</td></tr>
    {% endfor %}
    </table>

    {% for error in editgaleria.errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
    <button id="testformset">Agregar Imagen</button>
    <input type="submit" name="submit" value="Submit" />


</form>



    <div id="galeria"></div>
</div>
   <!-- menu lateral admin-->
<div class="lateral-menu">
    <ul>
        <li>
            <a class="salir-li" href="{% url 'adminlio:homeadmin' %}">{% trans 'Home' %}</a>
        </li>
        <li >
            <a class="salir-li" href="{% url 'adminlio:listproductos' %}">{% trans 'Product List' %}</a>
        </li>
        <li >
            <a class="salir-li" href="{% url 'adminlio:creategallery' %}">{% trans 'Create gallery' %}</a>
        </li>
         <li >
            <a class="salir-li" href="{% url 'adminlio:listgallery' %}">{% trans 'List gallery' %}</a>
        </li>
        <li>
            <a class="salir-li" href="{% url 'adminlio:salir' %}">{% trans 'Log Out' %}</a>
        </li>
    </ul>
</div>

    <script>
        window.location.hash="no-back-button";
        window.location.hash="Again-No-back-button";//again because google chrome don't insert first hash into history
        window.onhashchange=function(){window.location.hash="no-back-button";}
    </script>

    <script type="text/javascript" src="{% static 'js/gallery.js' %}"></script>
    <script type="text/javascript">
    </script>
</body>
</html>

templates/galeria/eliminar_galeria.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
<form method="post">
    {% csrf_token %}
    <h3>¿Desea el registro de {{ galeria.title }}?</h3>
    <button type="submit">Sí,eliminar</button>
    <a href="{% url 'adminlio:listgallery' %}">Cancelar</a>
</form>

templates/galeria/galeria.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>lio admin</title>
    <link rel="stylesheet" href="{% static 'css/adminlio.css' %}" type="text/css">
    <script>
         var static_url = "{% get_static_prefix %}";
        var media_url = "{% get_media_prefix %}";
        var juipo = 'probando';
    </script>
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>


</head>
<body>
<h1 style="background-color: #0acc54;padding: 10px;border-radius: 10px 0 10px 0;color:white;">Create Gallery</h1>
<div style="position: absolute; left: 40%;top: 27.5%; width: 35%; height: 70%; background-color: #00A6D8; overflow-y: scroll">
    <form id="post_form" method="post" action="" enctype="multipart/form-data">

    {% csrf_token %}
    {{ form.as_p }}
    <!--{% for field in postForm %}
        {{ field }} <br />
                    {% endfor %} -->

    {{ creategaleria.management_form }}
    <table id="aditional-items">
       {% for field in creategaleria %}
        <tr><td>{{ field }}</td></tr>
    {% endfor %}
    </table>

    {% for error in creategaleria.errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
    <button id="testformset">Agregar Imagen</button>
    <input type="submit" name="submit" value="Submit" />


</form>



    <div id="galeria"></div>
</div>
   <!-- menu lateral admin-->
<div class="lateral-menu">
    <ul>
        <li>
            <a class="salir-li" href="{% url 'adminlio:homeadmin' %}">{% trans 'Home' %}</a>
        </li>
        <li >
            <a class="salir-li" href="{% url 'adminlio:listproductos' %}">{% trans 'Product List' %}</a>
        </li>
        <li >
            <a class="salir-li" href="{% url 'adminlio:creategallery' %}">{% trans 'Create gallery' %}</a>
        </li>
         <li >
            <a class="salir-li" href="{% url 'adminlio:listgallery' %}">{% trans 'List gallery' %}</a>
        </li>
        <li>
            <a class="salir-li" href="{% url 'adminlio:salir' %}">{% trans 'Log Out' %}</a>
        </li>
    </ul>
</div>

    <script>
        window.location.hash="no-back-button";
        window.location.hash="Again-No-back-button";//again because google chrome don't insert first hash into history
        window.onhashchange=function(){window.location.hash="no-back-button";}
    </script>

    <script type="text/javascript" src="{% static 'js/gallery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/adminlio.js' %}"></script>
    <script type="text/javascript">
    </script>
</body>
</html>

templates/galeria/listgalerias.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link  rel="stylesheet" type="text/css" href="{% static 'css/adminlio.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <style>
        /*FUENTES TIPOGRAFICAS PARA LA PAGINA*/
        @font-face
        {
            font-family: shakeoffchunki;
            src: url("{% static 'fonts/KGShakeitOffChunky.ttf' %}");
        }

        @font-face
        {
            font-family: BROMO;
            src: url("{% static 'fonts/BROMO.otf'%}");
        }

        @font-face
        {
            font-family: shakeoff;
            src: url("{% static 'fonts/KGShakeitOff.ttf' %}");
        }
        table
        {
            width: 80%;
            position: absolute;
            left: 18%;
            border-spacing: 0;
            border-right: 1px solid #ccc;
            font-family: Serif;
            border-bottom: solid 1px #ccc;
        }
        thead
        {
            background-color: #00cccd;
            font-size: 1.2em;
            color: white;
            text-align: center;

        }
        table tbody tr
        {
            background-color: #ffffff;
            color: #000000;
            text-align: center;
        }
        table tbody tr:hover
        {
            background-color: #b2b2b2;
            color: #f4f4f4;
            text-align: center;
        }
        td,th
        {
             border-left: 1px solid #ccc;
             border-top: 1px solid #ccc;
        }
         #title_listproducts
        {
            text-align: center;
        }
        #title_listproducts span
        {
            padding: 10px;
            background-color: #1e15bd;
            color: white;
            font-family: shakeoffchunki;
            text-align: center;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <br>
    <br>
    <div><h1 id="title_listproducts"><span>{% trans 'List of galleries' %}</span></h1></div>

    <!--<a style="position: fixed; top:2%; left: 95%;text-decoration: none;background-color: #1e15bd;color: white;border-radius: 3px;padding: 5px; font-family: shakeoffchunki" href="{% url 'adminlio:salir' %}">Salir</a>-->
    <br>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>{% trans 'Name' %}</th>
                <th>{% trans 'Description' %}</th>
                <th>{% trans 'Edit' %}</th>
                <th>{% trans 'Delete' %}</th>
            </tr>
        </thead>
        <tbody>
            {% if galerias %} <!-- si hay mascotas en el contexto if mascotas usando vistas como funciones-->
                {% for galeria in galerias %}
                <tr>
                    <td>{{ galeria.id }}</td>
                    <td>{{ galeria.title }}</td>
                    <td>{{ galeria.body }}</td>
                    <td>
                        <a href="{% url 'adminlio:editgallery' galeria.id %}" style="text-decoration: none;background-color: #1e15bd;color: white;border-radius: 3px;padding: 5px;">{% trans 'Edit' %}</a> <!-- mascota.id es para que nos mande a la direccion del id que queremos modificar-->
                    </td>
                    <td>
                        <a href="{% url 'adminlio:deletegallery' galeria.id %}" style="text-decoration: none;background-color: #fc2e3c;color: white;border-radius: 3px;padding: 5px;">{% trans 'Delete' %}</a> <!-- mascota.id es para que nos mande a la direccion del id que queremos modificar-->
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                   <h1> No hay registros de galerias</h1>
            {% endif %}
        </tbody>
    </table>
    <!-- menu lateral admin-->
<div class="lateral-menu">
    <ul>
        <li>
            <a class="salir-li" href="{% url 'adminlio:homeadmin' %}">{% trans 'Home' %}</a>
        </li>
        <li >
            <a class="salir-li" href="{% url 'adminlio:listproductos' %}">{% trans 'Product List' %}</a>
        </li>
        <li >
            <a class="salir-li" href="{% url 'adminlio:creategallery' %}">{% trans 'Create gallery' %}</a>
        </li>
        <li>
            <a class="salir-li" href="{% url 'adminlio:salir' %}">{% trans 'Log Out' %}</a>
        </li>
    </ul>
</div>
    <script type="text/javascript" >
        $.ajax({
           url : 'zonas',
           type: 'get',
           data : {},

           success : function(json) {
               //alert(json.devuelto.length);
               // pinta el svg con datos de las zonas en la base de datos

               var shadow_object_img = document.querySelectorAll('[id*=list_prod]');
               $(shadow_object_img).on('load',function () {
                   for (var prod = 0; prod < shadow_object_img.length; prod++)
                   {
                       //activamos el evento load para cada object. Este evento cargara los colores del mismo desde la db

                       //$(this.object_img[prod]).unbind('load');
                        (function (x)
                       {
                               var svgobject = shadow_object_img[x].contentDocument;
                               var zonasclick = svgobject.querySelectorAll("[id^=click]");
                               for (var zona = 0; zona < zonasclick.length; zona++) {
                                   svgobject.querySelector('#' + zonasclick[zona].id.slice(5) + ' image').setAttribute('xlink:href', '/media/' + json.zone[x][zona]['color_zona__file_color']);
                                   console.log(json.zone[x][zona]['color_zona__file_color']);
                               }

                       })(prod);


                   }
               });


           }
               //$('#prevsvg').attr('data','../../media/'+ json.daticos[0].file_troquel);
           ,

            error : function(xhr,errmsg,err)
            {
                alert(err);
            }
        });
    </script>
</body>
</html>