adminlio/urls.py
from django.conf.urls import url
from django.contrib import admin

from sys import path
from django.conf.urls import url,include
from django.contrib import admin
from login.views import LoginAdmin
from adminlio.views import adminhome,savetroquel,findtroqueles,edittroqueles,deletetroqueles,updatetroquel,addcolor,getcolores,CreateGallery,showpost,showimagenes,Listaproductos,getzonesforproduct,EditarProducto,EliminarProducto,repeattroquel,EditGallery,Listagalerias,EliminarGaleria,validate_troquel
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import javascript_catalog
from django.contrib.auth.views import logout


js_info_dict = {
    #domain is default
    'packages': ('adminlio',),
}
urlpatterns = [
    url(r'^$', adminhome.as_view(), name="homeadmin"),
    url(r'^login$', LoginAdmin.as_view(), name="loginadmin"),
    url(r'^savetroquel$',savetroquel , name="savetroquel"),
    url(r'^repeattroquel$',repeattroquel , name="repeattroquel"),
    url(r'^findtroquel$',findtroqueles , name="findtroquel"),
    url(r'^updatetroquel$',updatetroquel , name="updatetroquel"),
    url(r'^creategallery',CreateGallery.as_view() , name="creategallery"),
    url(r'^editgallery/(?P<pk>\d+)$',EditGallery.as_view() , name="editgallery"),
    url(r'^listgallery',Listagalerias , name="listgallery"),
    url(r'^deletegallery/(?P<pk>\d+)$',EliminarGaleria.as_view() , name="deletegallery"),
    url(r'^getcolores$',getcolores, name="getcolores"),
    url(r'^addcolor$',addcolor , name="addcolor"),
    url(r'^edittroqueles/(?P<pk>\d+)$',edittroqueles , name="edittroqueles"),
    url(r'^deletetroqueles/(?P<pk>\d+)$',deletetroqueles , name="deletetroqueles"),
    url(r'^editarproducto/(?P<pk>\d+)$',EditarProducto.as_view(),name="editarproducto"),
    url(r'^elmininarproducto/(?P<pk>\d+)$',EliminarProducto.as_view(),name="eliminarproducto"),

    url(r'^validatetroquel$', validate_troquel, name="validatetroquel"),

    url(r'^listproductos',Listaproductos,name='listproductos'),
    url(r'^zonas$', getzonesforproduct, name="zonas"),
    #url(r'^registro/', AddAdmin.as_view(), name='registroadmin'),
    url(r'^salir$', logout, name="salir", kwargs={'next_page': 'adminlio:loginadmin'})
]

login/urls.py
from django.conf.urls import url
from django.contrib import admin

from sys import path
from django.conf.urls import url,include
from django.contrib import admin
from login.views import Loginusuario, AddUsuario
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import javascript_catalog
from django.contrib.auth.views import logout

js_info_dict = {
    #domain is default
    'packages': ('login',),
}
urlpatterns = [
    url(r'^$', Loginusuario.as_view(), name="login"),
    url(r'^registro/', AddUsuario.as_view(), name='registro'),
    url(r'^salir$', logout, name="salir", kwargs={'next_page': 'login:login'})
]

madebylio/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from base.views import home,showproducts
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import javascript_catalog
from django.contrib.staticfiles.urls import static
from adminlio.views import showimagenes,showpost
from login.views import loginajax,userregajax
from base.views import send_mail,findprodforcategory,savebuy,retrieve_data,fillmobileshopcar,validate_username,cleancookies,savecanvasimage,chargecolors,showsameproducts,test_query,hometeste
from adminlio.views import validate_troquel
from django.contrib.auth.views import logout
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm,password_reset_complete

js_info_dict = {
    #domain is default
    'packages': ('base',),
}
urlpatterns = [

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
        url(_(r'^admin/'), admin.site.urls),
        url(_(r'^login/'), include('login.urls', namespace='login')),
        url(_(r'^adminlio/'), include('adminlio.urls', namespace='adminlio')),
        url(_(r'^pagos/'), include('pagos.urls', namespace='pagos')),
        url(_(r'^$'), home,name='home'),
        url(_(r'^teste'), hometeste,name='hometeste'),
        #url(_(r'^oauth/'), include('social_django.urls', namespace='social')),  # <-- social auth
        url(_(r'accounts/'),include('allauth.urls')),
        url(_(r'^cleancookies$'), cleancookies,name='cleancookies'),
        url(_(r'^showsameproducts$'), showsameproducts,name='showsameproducts'),
        url(_(r'chargecolors$'), chargecolors,name='chargecolors'),
        url(_(r'^savecanvas$'), savecanvasimage,name='savecanvas'),
        url(_(r'^savebuy$'), savebuy,name='savebuy'),
        url(_(r'^testquery$'), test_query,name='testquery'),
        url(_(r'^fillmobileshopcar$'), fillmobileshopcar,name='fillmobileshopcar'),
        url(_(r'^pagos/retrieve_data$'), savebuy,name='retrieve_data'),
        url(r'^send-mail$',send_mail , name="send-mail"),       
        url(r'^loginuser$', loginajax, name="loginuser"),
        url(r'^reguser$', userregajax, name="reguser"),
        url(_(r'^showproducts$'), showproducts,name='showproducts'),
        url(_(r'^validateusername$'), validate_username,name='validateusername'),
        url(_(r'^showimagenes$'),showimagenes, name="showimages"),
        url(_(r'^showgalleries$'),showpost, name="showgalleries"),
        url(_(r'^showprodforcategories'),findprodforcategory,name='showprodforcategories'),
        url(_(r'^salir$'), logout, name="salirhome", kwargs={'next_page': 'home'}),
        #url para recuperar contraseña
        url(_(r'^reset/password_reset/$'),password_reset,{'template_name':'registration/password_reset_form.html','email_template_name':'registration/password_reset_email.html'},name='password_reset'),
                url(_(r'^reset/password_reset_done/$'),password_reset_done,{'template_name':'registration/password_reset_done.html'},name='password_reset_done'),
                url(_(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$'),password_reset_confirm, {'template_name':'registration/password_reset_confirm.html'},name='password_reset_confirm'),
                url(_(r'^reset/done/$'),password_reset_complete,{'template_name':'registration/password_reset_complete.html'},name="password_reset_complete"),
        url(r'^i18n/',include('django.conf.urls.i18n')),
        url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),
)

adminlio/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect, JsonResponse,HttpResponse
from django.views.generic import CreateView, TemplateView,View, DetailView,ListView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from login.views import LoginAdmin
from adminlio.forms import TroquelForm,ZonaFormSet,ProductoForm,ColorForm,ZonaEFormSet
from adminlio.models import Troquel,UsuarioAdmin,Producto,Color,Zona
from galeria.models import Postgallery
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.shortcuts import redirect
from django.db import transaction
from galeria.models import Postgallery,Imagegallery
from django.forms.models import inlineformset_factory,modelformset_factory
from galeria.forms import ImageForm,PostForm,GalleryFormSet
from django.contrib import messages
import json


decorators = [permission_required('adminlio.add_usuarioaw')]

class adminhome(CreateView):

    success_url = reverse_lazy("adminlio:homeadmin")
    model = Producto
    template_name = "adminlio/index.html"
    fields = ['nombre_producto', 'troquel_producto', 'pais_producto', 'ciudad_producto', 'precio_producto', 'cantidad_producto','descripcion_producto','tamano_producto','img_producto','video_producto','prev_producto','pattern_producto']

    def dispatch(self, request, *args, **kwargs):
        # Si el usuario está autenticado entonces nos direcciona a la url establecida en success_url
        if request.user.is_authenticated() and request.user.is_superuser:
            return super(adminhome, self).dispatch(request, *args, **kwargs)
        # Sino lo está entonces nos muestra la plantilla del login simplemente
        else:
            return HttpResponseRedirect(reverse_lazy('adminlio:loginadmin'))

    def get_context_data(self, **kwargs):
        data = super(adminhome, self).get_context_data(**kwargs)
        if self.request.POST:
            data['crearzona'] = ZonaFormSet(self.request.POST)
        else:
            form_troquel = TroquelForm()
            data['choices_type'] = form_troquel
            data['crearzona'] = ZonaFormSet()
            usuario = self.request.user
            queryset = UsuarioAdmin.objects.filter(username__icontains=usuario)
            self.my_object = get_object_or_404(queryset)
            data['userinfo'] = self.my_object  # enviando mas de un dato al template
            #data['crearzona'] = ZonaFormSet()
            #usuario = self.request.user
            #queryset = Usuario.objects.filter(username__icontains=usuario)
            #self.my_object = get_object_or_404(queryset)
            #data['userinfo'] = self.my_object  # enviando mas de un dato al template
        return data
    def form_valid(self, form):
        context = self.get_context_data()
        #form.instance.user = self.request.user #obtenemos el user
        zonas = context['crearzona']
        with transaction.atomic(): #CREAMOS COMUNICACION ASINCRONA CON LA BASE DE DATOS
            self.object = form.save()

            if zonas.is_valid(): #VERICAMOS QUE LOS CAMPOS DEL FORMULARIOS
                zonas.instance = self.object
                zonas.save()
        return super(adminhome, self).form_valid(form)

class EditarProducto(UpdateView):
    success_url = reverse_lazy("adminlio:listproductos")
    model = Producto
    template_name = "adminlio/editar_producto.html"
    fields = ['nombre_producto', 'troquel_producto', 'pais_producto', 'ciudad_producto', 'precio_producto','cantidad_producto', 'descripcion_producto','tamano_producto','img_producto','video_producto','prev_producto','pattern_producto']

    def get_context_data(self, **kwargs):  # CREAMOS EL CONTEXTO PARA NUESTRA PAGINA
        data = super(EditarProducto, self).get_context_data(**kwargs)

        if self.request.POST:
            data['crearzona'] = ZonaEFormSet(self.request.POST, instance=self.object)
        else:
            data['crearzona'] = ZonaEFormSet(instance=self.object)
            data['odo'] = Producto.objects.filter(nombre_producto=self.object).values('troquel_producto__file_troquel')[0]

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        editarzona = context['crearzona']
        with transaction.atomic():
            self.object = form.save()
            if editarzona.is_valid():
                editarzona.instance = self.object
                editarzona.save()
        return super(EditarProducto, self).form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        # Si el usuario está autenticado entonces nos direcciona a la url establecida en success_url
        if request.user.is_authenticated() and request.user.is_superuser:
            return super(EditarProducto, self).dispatch(request, *args, **kwargs)
        # Sino lo está entonces nos muestra la plantilla del login simplemente
        else:
            return HttpResponseRedirect(reverse_lazy('adminlio:loginadmin'))


class EliminarProducto(DeleteView):
    model = Producto
    template_name = 'adminlio/eliminar_producto.html'
    success_url = reverse_lazy('adminlio:listproductos')


    def dispatch(self, request, *args, **kwargs):
        # Si el usuario está autenticado entonces nos direcciona a la url establecida en success_url
        if request.user.is_authenticated() and request.user.is_superuser:
            return super(EliminarProducto, self).dispatch(request, *args, **kwargs)
        # Sino lo está entonces nos muestra la plantilla del login simplemente
        else:
            return HttpResponseRedirect(reverse_lazy('adminlio:loginadmin'))

#VISTA AJAX PARA GUARDAR TROQUELES
def savetroquel(request):
    data = dict()
    instancia = TroquelForm(request.POST, request.FILES)
    if instancia.is_valid() and request.method == 'POST' and request.FILES:
        guardado = instancia.save()
    else:
        TroquelForm()
        data['error'] = 'no guardo'
    return JsonResponse(data)

def repeattroquel(request):
    data = dict()
    troquel = request.GET.get('troquel')
    instancia = Troquel.objects.filter(file_troquel__exact=troquel).values('file_troquel')
    return JsonResponse({'resultado':list(instancia)})

def findtroqueles(request):
    troquel = dict()
    if request.method == 'GET':
        if request.is_ajax():
            nombre = request.GET.get('nombre')
            size = request.GET.get('size')
            category = request.GET.get('category')
            troquel = Troquel.objects.filter(Q(categoria_troquel__contains=category)& Q(nombre_troquel__contains=nombre)).values('id','nombre_troquel','file_troquel')
            #troquel = Troquel.objects.all().values('nombre_troquel')
    return JsonResponse({'devuelto':list(troquel)})  # , HttpResponse(guardado.file.name)
    #User.objects.filter(
    #    Q(first_name__startswith='R') & ~Q(last_name__startswith='Z')
    #)

def edittroqueles(request,pk):
    edittroquel = ''
    data = dict()
    write = 'asdasd'
    primary = request.GET.get('id')
    troquel = get_object_or_404(Troquel, id=pk)
    #troquel = get_object_or_404(Troquel, pk=pk)
    #resultado = ''
    if request.method == 'POST':
        edittroquel = TroquelForm(request.POST, request.FILES, instance=troquel)
        if edittroquel.is_valid():
            edittroquel.save()
            resultado = 'guardado exitosamente'
            #data['respuesta'] = resultado
            data['html_content'] = render_to_string('plantillas_html/successtroqueledit.html', {'tformedit': resultado },request=request)
            return redirect('adminlio:homeadmin')

    else:
        resultado = 'editando'
        data['respuesta'] = resultado
        edittroquel = TroquelForm(instance=troquel)
        data['html_content'] = render_to_string('plantillas_html/edittroquelform.html', {'tformedit': edittroquel,'valueid':primary},request=request)
        return JsonResponse(data)

def deletetroqueles(request,pk):
    data = dict()
    write = 'asdasd'
    primary = request.GET.get('id')
    troquel = get_object_or_404(Troquel, id=pk)
    # troquel = get_object_or_404(Troquel, pk=pk)
    # resultado = ''
    if request.method == 'POST':
        #deletetroquel = TroquelForm(request.POST, request.FILES, instance=troquel)
        troquel.delete()
        resultado = 'guardado exitosamente'
        # data['respuesta'] = resultado
        data['html_content'] = render_to_string('plantillas_html/successtroqueledit.html', {'tformedit': resultado},request=request)
        return redirect('adminlio:homeadmin')

    else:
        #deletetroquel = TroquelForm(instance=troquel)
        data['html_content'] = render_to_string('plantillas_html/deletetroquelform.html',
                                                {'valueid': primary}, request=request)
        return JsonResponse(data)

def updatetroquel(request): #vista que me actualiza troqueles dentrod el formulario de productos Y ADEMAS DE UNA VEZ CARGAMOS LA INFORMACION DE TROQUEL SELECCIONADO PARA CREAR EL PRODUCTO
    primary = request.GET.get('id')
    troquel = Troquel.objects.filter(id=primary).values('file_troquel','editable_troquel')
    alltroquel = Troquel.objects.all().values('id', 'nombre_troquel', 'file_troquel','editable_troquel')
    # img = {'dato':dato}
    return JsonResponse({'data_troquel': list(alltroquel),'troquel':list(troquel)})

    # VISTA AJAX PARA GUARDAR TROQUELES
def addcolor(request):
    data = dict()
    instancia = ColorForm(request.POST, request.FILES)
    if instancia.is_valid() and request.method == 'POST' and request.FILES:

        guardado = instancia.save()
        data['color_form'] = 'guardado exitosamente'
    else:
        ColorForm()
        data['color_form'] = 'guardado exitosamente'

    return JsonResponse(data)

templates/adminlio/confirm.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
<p style="text-align: center"><span style="position: relative; font-family: shakeoff; background-color: #03f345;color: white; padding: 5px; font-size: 2em;border-radius: 5px">CONFIRMAR PRODUCTO</span></p>
<div class="checkout-product">

        <object id=checkout-prod" style="width:100%; height: 100%" data="{% static 'img/lioadmin/confirmacion/cont_formulario_confirmacion.svg'%}"  type="image/svg+xml">

        </object>
        <div id="cont-confirm-data" style="font-family: shakeoff; color: #ffffff;">
            {% include 'plantillas_html/confirm_interface.html' %}
        </div>
        <button id="confirm-producto-btn" type="button">
                Finalizar
        </button>
</div>
<div class="upload-process">

        <object id=process" style="width:100%; height: 100%" data="{% static 'img/lioadmin/en_comun/cont_proceso.svg'%}"  type="image/svg+xml">

        </object>

</div>

<div id="volver-productos">Volver</div>

<!-- menu lateral admin-->
    <div class="lateral-menu">
        <ul>
            <li >
                <a class="salir-li" href="{% url 'adminlio:listproductos' %}">{% trans 'Product List' %}</a>
            </li>
            <li>
                <a class="salir-li" href="{% url 'adminlio:salir' %}">{% trans 'Log Out' %}</a>
            </li>
        </ul>
    </div>

templates/adminlio/eliminar_producto.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
<form method="post">
    {% csrf_token %}
    <h3>¿Desea el registro de {{ producto.nombre_producto }}?</h3>
    <button type="submit">Sí,eliminar</button>
    <a href="{% url 'adminlio:listproductos' %}">Cancelar</a>
</form>

templates/adminlio/listproductos.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link  rel="stylesheet" type="text/css" href="{% static 'css/adminlio.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <style>
        /*FUENTES TIPOGRAFICAS PARA LA PAGINA*/
        @font-face
        {
            font-family: shakeoffchunki;
            src: url("{% static 'fonts/KGShakeitOffChunky.ttf' %}");
        }

        @font-face
        {
            font-family: BROMO;
            src: url("{% static 'fonts/BROMO.otf'%}");
        }

        @font-face
        {
            font-family: shakeoff;
            src: url("{% static 'fonts/KGShakeitOff.ttf' %}");
        }
        table
        {
            width: 80%;
            position: absolute;
            left: 18%;
            border-spacing: 0;
            border-right: 1px solid #ccc;
            font-family: Serif;
            border-bottom: solid 1px #ccc;
        }
        thead
        {
            background-color: #00cccd;
            font-size: 1.2em;
            color: white;
            text-align: center;

        }
        table tbody tr
        {
            background-color: #ffffff;
            color: #000000;
            text-align: center;
        }
        table tbody tr:hover
        {
            background-color: #b2b2b2;
            color: #f4f4f4;
            text-align: center;
        }
        td,th
        {
             border-left: 1px solid #ccc;
             border-top: 1px solid #ccc;
        }
         #title_listproducts
        {
            text-align: center;
        }
        #title_listproducts span
        {
            padding: 10px;
            background-color: #1e15bd;
            color: white;
            font-family: shakeoffchunki;
            text-align: center;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <br>
    <br>
    <div><h1 id="title_listproducts"><span>Lista de productos</span></h1></div>

    <!--<a style="position: fixed; top:2%; left: 95%;text-decoration: none;background-color: #1e15bd;color: white;border-radius: 3px;padding: 5px; font-family: shakeoffchunki" href="{% url 'adminlio:salir' %}">Salir</a>-->
    <br>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Troquel</th>
                <th>Pais</th>
                <th>Ciudad</th>
                <th>Precio</th>
                <th>Cantidad</th>
                <th>Imagen</th>
                <th>Editar</th>
                <th>Borrar</th>
            </tr>
        </thead>
        <tbody>
            {% if productos %} <!-- si hay mascotas en el contexto if mascotas usando vistas como funciones-->
                {% for producto in productos %}
                <tr>
                    <td>{{ producto.id }}</td>
                    <td>{{ producto.nombre_producto }}</td>
                    <td>{{ producto.troquel_producto__nombre_troquel }}</td>
                    <td>{{ producto.pais_producto}}</td>
                    <td>{{ producto.ciudad_producto }}</td>
                    <td>{{ producto.precio_producto }}</td>
                    <td>{{ producto.cantidad_producto }}</td>
                    <td>
                        <object id="list_prod{{ forloop.counter0 }}" data="/media/{{ producto.troquel_producto__file_troquel}}" type="image/svg+xml" style="width: 100px;height: 100px;">

                        </object>
                   </td>
                    <td>
                        <a href="{% url 'adminlio:editarproducto' producto.id %}" style="text-decoration: none;background-color: #1e15bd;color: white;border-radius: 3px;padding: 5px;">Editar</a> <!-- mascota.id es para que nos mande a la direccion del id que queremos modificar-->
                    </td>
                    <td>
                        <a href="{% url 'adminlio:eliminarproducto' producto.id %}" style="text-decoration: none;background-color: #fc2e3c;color: white;border-radius: 3px;padding: 5px;">Eliminar</a> <!-- mascota.id es para que nos mande a la direccion del id que queremos modificar-->
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                   <h1> No hay registros de productos</h1>
            {% endif %}
        </tbody>
    </table>
    <!-- menu lateral admin-->
<div class="lateral-menu">
    <ul>
        <li>
            <a class="salir-li" href="{% url 'adminlio:homeadmin' %}">{% trans 'Home' %}</a>
        </li>
        <li >
            <a class="salir-li" href="{% url 'adminlio:listproductos' %}">{% trans 'Product List' %}</a>
        </li>
        <li >
            <a class="salir-li" href="{% url 'adminlio:creategallery' %}">{% trans 'Create gallery' %}</a>
        </li>
         <li >
            <a class="salir-li" href="{% url 'adminlio:listgallery' %}">{% trans 'List gallery' %}</a>
        </li>
        <li>
            <a class="salir-li" href="{% url 'adminlio:salir' %}">{% trans 'Log Out' %}</a>
        </li>
    </ul>
</div>
    <script type="text/javascript" >
        $.ajax({
           url : 'zonas',
           type: 'get',
           data : {},

           success : function(json) {
               //alert(json.devuelto.length);
               // pinta el svg con datos de las zonas en la base de datos

               var shadow_object_img = document.querySelectorAll('[id*=list_prod]');
               $(shadow_object_img).on('load',function () {
                   for (var prod = 0; prod < shadow_object_img.length; prod++)
                   {
                       //activamos el evento load para cada object. Este evento cargara los colores del mismo desde la db

                       //$(this.object_img[prod]).unbind('load');
                        (function (x)
                       {
                               var svgobject = shadow_object_img[x].contentDocument;
                               var zonasclick = svgobject.querySelectorAll("[id^=click]");
                               for (var zona = 0; zona < zonasclick.length; zona++) {
                                   svgobject.querySelector('#' + zonasclick[zona].id.slice(5) + ' image').setAttribute('xlink:href', '/media/' + json.zone[x][zona]['color_zona__file_color']);
                                   console.log(json.zone[x][zona]['color_zona__file_color']);
                               }

                       })(prod);


                   }
               });


           }
               //$('#prevsvg').attr('data','../../media/'+ json.daticos[0].file_troquel);
           ,

            error : function(xhr,errmsg,err)
            {
                alert(err);
            }
        });
    </script>
</body>
</html>

templates/adminlio/noperm.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    no tienes permisos
    <a href="{% url 'adminlio:loginadmin' %}">Volver...</a>
</body>
</html>

templates/adminlio/producto.html
{% load i18n %}
{% load l10n %}
{% load tz %}
{% load staticfiles %}
{% load static %}

<!--
<div  class="producto-findbtn">

        <object id="findbtn" style="width:100%; height: 100%" data="{% static 'img/lioadmin/en_comun/boton_buscar_menu_02.svg'%}"  type="image/svg+xml">

        </object>

</div>

<div id="mask-producto-findbtn" class="troquel-findbtn">

</div>

<div class="producto-addbtn">

        <object id="findbtn" style="width:100%; height: 100%" data="{% static 'img/lioadmin/en_comun/boton_nuevo_menu_02.svg'%}"  type="image/svg+xml">

        </object>

</div>

<div id="mask-producto-addbtn" class="producto-addbtn">

</div> -->

<div class="upload-process">

        <object id=process" style="width:100%; height: 100%" data="{% static 'img/lioadmin/en_comun/cont_proceso.svg'%}"  type="image/svg+xml">

        </object>

</div>

<div class="producto-check">

        <object id="checkproducto" style="width:100%; height: 100%" data="{% static 'img/lioadmin/en_comun/boton_ok.svg'%}"  type="image/svg+xml">

        </object>

</div>

<div id="mask-producto-check" class="producto-check">

</div>

<div class="producto-newproducto">

        <!--<object id=newproducto" style="width:100%; height: 100%" data="{% static 'img/lioadmin/nuevo/cont_formulario_nuevo.svg'%}"  type="image/svg+xml">

        </object>-->

        <div id="cont-createproductform">
            {% include 'plantillas_html/form_productos.html' %}

        </div>
</div>

<div id="add-color">
    Add color!
</div>

<input id="how-zones" type="hidden">
<input id="save-troquel" type="hidden">
<div id="crear-producto-btn" type="button" class="pretty-btn">
                Crear
</div>
<div id="volver-troquel">Volver</div>
<div id="cont-add-color">
    {% include 'plantillas_html/form_colors.html' %}
</div>

<!-- menu lateral admin-->
    <div class="lateral-menu">
        <ul>
            <li>
            <a class="salir-li" href="{% url 'adminlio:homeadmin' %}">{% trans 'Home' %}</a>
        </li>
        <li >
            <a class="salir-li" href="{% url 'adminlio:listproductos' %}">{% trans 'Product List' %}</a>
        </li>
            <li >
            <a class="salir-li" href="{% url 'adminlio:creategallery' %}">{% trans 'Create gallery' %}</a>
        </li>
         <li >
            <a class="salir-li" href="{% url 'adminlio:listgallery' %}">{% trans 'List gallery' %}</a>
        </li>
            <li>
                <a class="salir-li" href="{% url 'adminlio:salir' %}">{% trans 'Log Out' %}</a>
            </li>
        </ul>
    </div>